// global
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';

// contest
export const CONTEST_LOAD_SUCCESS = 'CONTEST_LOAD_SUCCESS';
export const CONTEST_ADD_SUCCESS = 'CONTEST_ADD_SUCCESS';
export const CONTEST_EDIT_SUCCESS = 'CONTEST_EDIT_SUCCESS';
export const CONTEST_DELETE_SUCCESS = 'CONTEST_DELETE_SUCCESS';
export const SHOW_TEST_TABLE = 'SHOW_TEST_TABLE';
export const HIDE_TEST_TABLE = 'HIDE_TEST_TABLE';

// contest delete
export const CONTEST_FORM_DELETE_OPEN = 'CONTEST_FORM_DELETE_OPEN';
export const CONTEST_FORM_DELETE_CLOSE = 'CONTEST_FORM_DELETE_CLOSE';

// contest form
export const CONTEST_FORM_OPEN = 'CONTEST_FORM_OPEN';
export const CONTEST_FORM_CLOSE = 'CONTEST_FORM_CLOSE';
export const CONTEST_FORM_SET_NAME = 'CONTEST_FORM_SET_NAME';
export const CONTEST_FORM_SET_DESCRIPTION = 'CONTEST_FORM_SET_DESCRIPTION';
export const CONTEST_FORM_SET_RESULT = 'CONTEST_FORM_SET_RESULT';
export const CONTEST_FORM_VALIDATE = 'CONTEST_FORM_VALIDATE';
export const MOVE_BACK = 'MOVE_BACK';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

// question
export const QUESTION_PAGE_OPEN = 'QUESTION_PAGE_OPEN';
export const QUESTION_LOAD_SUCCESS = 'QUESTION_LOAD_SUCCESS';
export const QUESTION_ADD_SUCCESS = 'QUESTION_ADD_SUCCESS';
export const QUESTION_EDIT_SUCCESS = 'QUESTION_EDIT_SUCCESS';
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS';
export const QUESTION_CHANGE = 'QUESTION_CHANGE';

// question form
export const QUESTION_FORM_OPEN = 'QUESTION_FORM_OPEN';
export const QUESTION_FORM_CLOSE = 'QUESTION_FORM_CLOSE';
export const QUESTION_FORM_SET_TEXT = 'QUESTION_FORM_SET_TEXT';
export const QUESTION_FORM_SET_TYPE = 'QUESTION_FORM_SET_TYPE';
export const QUESTION_FORM_VALIDATE = 'QUESTION_FORM_VALIDATE';
export const QUESTION_FORM_QUESTION_TYPE_LOAD_SUCCESS = 'QUESTION_FORM_QUESTION_TYPE_LOAD_SUCCESS';

// question delete
export const QUESTION_FORM_DELETE_OPEN = 'QUESTION_FORM_DELETE_OPEN';
export const QUESTION_FORM_DELETE_CLOSE = 'QUESTION_FORM_DELETE_CLOSE';

// answer
export const ANSWER_PAGE_OPEN = 'ANSWER_PAGE_OPEN';
export const ANSWER_LOAD_SUCCESS = 'ANSWER_LOAD_SUCCESS';
export const ANSWER_ADD_SUCCESS = 'ANSWER_ADD_SUCCESS';
export const ANSWER_EDIT_SUCCESS = 'ANSWER_EDIT_SUCCESS';
export const ANSWER_DELETE_SUCCESS = 'ANSWER_DELETE_SUCCESS';

// answer form
export const ANSWER_FORM_OPEN = 'ANSWER_FORM_OPEN';
export const ANSWER_FORM_CLOSE = 'ANSWER_FORM_CLOSE';
export const ANSWER_FORM_SET_TEXT = 'ANSWER_FORM_SET_TEXT';
export const ANSWER_FORM_SET_TYPE = 'ANSWER_FORM_SET_TYPE';
export const ANSWER_FORM_VALIDATE = 'ANSWER_FORM_VALIDATE';
export const ANSWER_FORM_ANSWER_TYPE_LOAD_SUCCESS = 'ANSWER_FORM_ANSWER_TYPE_LOAD_SUCCESS';
export const ANSWER_FORM_SET_CORRECT = 'ANSWER_FORM_SET_CORRECT';

// answer form delete
export const ANSWER_FORM_DELETE_OPEN = 'ANSWER_FORM_DELETE_OPEN';
export const ANSWER_FORM_DELETE_CLOSE = 'ANSWER_FORM_DELETE_CLOSE';

// client groups
export const CLIENT_GROUP_LOAD_SUCCESS = 'CLIENT_GROUP_LOAD_SUCCESS';
export const CLIENT_GROUP_ADD_SUCCESS = 'CLIENT_GROUP_ADD_SUCCESS';
export const CLIENT_GROUP_EDIT_SUCCESS = 'CLIENT_GROUP_EDIT_SUCCESS';
export const CLIENT_GROUP_DELETE_SUCCESS = 'CLIENT_GROUP_DELETE_SUCCESS';
export const CLIENT_GROUP_CHANGE = 'CLIENT_GROUP_CHANGE';

// client groups form
export const CLIENT_GROUP_FORM_OPEN = 'CLIENT_GROUP_FORM_OPEN';
export const CLIENT_GROUP_FORM_CLOSE = 'CLIENT_GROUP_FORM_CLOSE';
export const CLIENT_GROUP_FORM_SET_NAME = 'CLIENT_GROUP_FORM_SET_NAME';
export const CLIENT_GROUP_FORM_VALIDATE = 'CLIENT_GROUP_FORM_VALIDATE';

// client groups form delete
export const CLIENT_GROUP_FORM_DELETE_OPEN = 'CLIENT_GROUP_FORM_DELETE_OPEN';
export const CLIENT_GROUP_FORM_DELETE_CLOSE = 'CLIENT_GROUP_FORM_DELETE_CLOSE';

// client
export const CLIENT_PAGE_OPEN = 'CLIENT_PAGE_OPEN';
export const CLIENT_LOAD_SUCCESS = 'CLIENT_LOAD_SUCCESS';
export const CLIENT_IN_GROUP_LOAD_SUCCESS = 'CLIENT_IN_GROUP_LOAD_SUCCESS';
export const CLIENT_ADD_SUCCESS = 'CLIENT_ADD_SUCCESS';
export const CLIENT_EDIT_SUCCESS = 'CLIENT_EDIT_SUCCESS';
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS';

// client form
export const CLIENT_FORM_OPEN = 'CLIENT_FORM_OPEN';
export const CLIENT_FORM_CLOSE = 'CLIENT_FORM_CLOSE';
export const CLIENT_FORM_SET_NAME = 'CLIENT_FORM_SET_NAME';
export const CLIENT_FORM_SET_EMAIL = 'CLIENT_FORM_SET_EMAIL';
export const CLIENT_FORM_VALIDATE = 'CLIENT_FORM_VALIDATE';

// client form delete
export const CLIENT_FORM_DELETE_OPEN = 'CLIENT_FORM_DELETE_OPEN';
export const CLIENT_FORM_DELETE_CLOSE = 'CLIENT_FORM_DELETE_CLOSE';

// manage client group
export const MANAGE_GROUP_OPEN = 'MANAGE_GROUP_OPEN';
export const MANAGE_GROUP_CLIENTS_IN_GROUP_LOAD_SUCCESS = 'MANAGE_GROUP_CLIENTS_IN_GROUP_LOAD_SUCCESS';
export const MANAGE_GROUP_ALL_CLIENTS_LOAD_SUCCESS = 'MANAGE_GROUP_ALL_CLIENTS_LOAD_SUCCESS';
export const MANAGE_GROUP_ADD_CLIENTS = 'MANAGE_GROUP_ADD_CLIENTS';
export const MANAGE_GROUP_REMOVE_CLIENTS = 'MANAGE_GROUP_REMOVE_CLIENTS';
export const MANAGE_GROUP_SAVE_GROUP_SUCCESS = 'MANAGE_GROUP_SAVE_GROUP_SUCCESS';

// distribution form
export const DISTRIBUTION_FORM_OPEN = 'DISTRIBUTION_FORM_OPEN';
export const DISTRIBUTION_FORM_CLOSE = 'DISTRIBUTION_FORM_CLOSE';
export const DISTRIBUTION_FORM_SET_TEXT = 'DISTRIBUTION_FORM_SET_TEXT';
export const DISTRIBUTION_FORM_SET_SUBJECT = 'DISTRIBUTION_FORM_SET_SUBJECT';
export const DISTRIBUTION_FORM_CREATE_DISTRIBUTION_SUCCESS = 'DISTRIBUTION_FORM_CREATE_DISTRIBUTION_SUCCESS';
export const DISTRIBUTION_FORM_LOAD_GROUPS_SUCCESS = 'DISTRIBUTION_FORM_LOAD_GROUPS_SUCCESS';
export const DISTRIBUTION_FORM_VALIDATE = 'DISTRIBUTION_FORM_VALIDATE';
